Change gitignore, rearrange folders.

diff --git a/Gaussian/Submit-SLM b/Gaussian/Submit-SLM
--- a/Gaussian/Submit-SLM
+++ b/Gaussian/Submit-SLM
@@ -3,28 +3,47 @@
 # Use Submit -h | --help to show usage.
 # Use this script at your own discretion.
 # This script automatically calibrates Link0 parms for .gjf files and then inject them through sbatch.
-# use -p to assign core numbers, -m to assign memory size (in GB) and -l to assign lindaworkers number.
 
 # !!!VERY IMPORTANT!!!
 # Multi-gjf simutaneous submit supported! (pass multiple filenames will do.)
 # if no %nprocs / %mem / %lindaworkers is assigned, original gjf parms will be respected.
 # IF ANY parameter is assigned a value (i.e. "-m 5"), it will be effective on the latter gjfs UNTIL it is re-assigned (i.e. "-m 4")
-# This script has gensub_g09 script embedded, but you still need gensub_g09_template file in ~/bin folder!
+# This script has gensub_g09/g16 script embedded, but you still need gensub_gauss_template file in ~/bin folder to make this script work!
 
-# Example: submit -p 12 -m 5 task1.gjf task2.gjf ...
+# Example: submit -p 12 -m 5 -q fat -g g16 -l 4 task1.gjf task2.gjf ...
 
-# RUN WITH PRECAUTION!
 # Created by Yuanqi Wang @CCMBI, Dec, 2018. Modification Allowed. Absolutely NO WARRANTY!
-######################################
+
+###########################################################
 
 # this script combines multiple commands:
 # 1. dos2unix <yourgjf>
 # 2. Adjust link0 resources parameters (nprocs / mem)
-# 3. genslm_g09 <yourgjf> (built in)
+# 3. gensub_gauss <yourgjf> (built in)
 # 4. Calibrate sub file
 # 5. sbatch <your_sub_bash_script>
 
-######################################
+###########################################################
+
+#>>>>>>>>>>>>>>>>>>>>  LOOK HERE  <<<<<<<<<<<<<<<<<<<<<<<<<
+# This is the section you should tweak before use:
+g09C01_root=/lustre/home/acct-clswxl/software/g09.C.01        # root dir of g09 C01 installation.
+g09C01_profile=$g09C01_root/g09/bsd/g09.profile               # profiles to be sources for g09
+
+g09D01_root=/lustre/home/acct-clswxl/software/g09.D.01        # root dir of g09 D01 installation.
+g09D01_profile=$g09D01_root/g09/bsd/g09.profile               # profiles to be sources for g09
+
+g09E01_root=/lustre/home/acct-clswxl/software/g09.E.01        # root dir of g09 E01 installation.
+g09E01_profile=$g09E01_root/g09/bsd/g09.profile               # profiles to be sources for g09
+
+g16A03_root=/lustre/home/acct-clswxl/software/g16.A.03        # root dir of g16 A03 installation.
+g16A03_profile=$g16A03_root/g16/bsd/g16.profile               # profiles to be sources for g16
+
+default_queue=fat                                             # default job queue.
+max_nprocs_per_node=16                                        # Maximum nprocs number per node.
+#>>>>>>>>>>>>>>>>>>>>  LOOK HERE  <<<<<<<<<<<<<<<<<<<<<<<<<
+
+###########################################################
 
 # Define colors
 NC='\033[0m'
@@ -37,7 +56,7 @@ Yellow='\033[1;33m'
 
 Blink='\033[5m'
 
-######################################
+###########################################################
 
 # Define Functions:
 
@@ -52,25 +71,27 @@ usage()
     printf "    [-m | --mem] ${Green}<Mem Size>${NC} ${Blue}...${NC} Assign ${Green}<Mem Size>${NC} to ${Red}%%mem${NC}.\n"
     printf "    [-p | --nprocs] ${Green}<Procs No.>${NC} ${Blue}...${NC} Assign ${Green}<Procs No.>${NC} to ${Red}%%nprocs${NC}.\n"
     printf "    [-q | --queue] ${Green}<Queue Name>${NC} ${Blue}...${NC} Change designated queue to ${Green}<Queue Name>${NC}.\n"
-    printf "    [-t | --test] make calibrations, but ${Red}${Blink}DOES NOT${NC} submit.\n\n"
+    printf "    [-g | --gauss] ${Green}<Gaussian Version>${NC} ${Blue}...${NC} Designate specific Gaussian Version.\n"
+    printf "                   Available versions: ${Blue}g09C01 / g09D01 / g09E01 / g16${NC} .\n"
+    printf "    [-t | --test] make calibrations, but ${Red}DOES NOT${NC} submit.\n\n"
     printf "${Red}DESCRIPTION${NC}\n\n"
     printf "  ${Yellow}\'Submit\'${NC} is used to calibrate Gaussian input files and inject through sbatch.\n"
     printf "  Arguments above can be mixed. each argument is effective ${Purple}until it is re-defined${NC}.\n"
     printf "  Wildcard supported. Try it out!\n"
-    printf "  Created with ${Red}LOVE${NC} by ${Blue}Yuanqi Wang${NC} ${Purple}@CCMBI${NC}(Dec, 2018). ${Yellow}${Blink}ABSOLUTELY NO WARRANTY!${NC}\n\n"
+    printf "  Created with ${Red}LOVE${NC} by ${Blue}Yuanqi Wang${NC} ${Purple}@CCMBI${NC}(Dec, 2018). ${Yellow}ABSOLUTELY NO WARRANTY!${NC}\n\n"
 }
 
-# built-in gensub_g09 function, adapted from original gensub_g09 script:
+# built-in gensub_g09/g16 function, adapted from original gensub_g09/g16 script:
    # example of $1 is: /path/to/gjf/example.gjf
-   # example of $2 is: middle (or low, etc.)
-genslm_g09_embedded()
+
+gen_gauss_embedded()
 {
     # parse directory / filename
-    gjf_dir=`dirname $1`  # get input file directory.           e.g. /path/to/gjf
-    gjf_file=`basename $1`       # filename without path.       e.g. example.gjf
-    gjf_name=${gjf_file%.*}      # filename without extension.  e.g. example
+    gjf_dir=`dirname $1`  # get input file directory.           i.e. /path/to/gjf
+    gjf_file=`basename $1`       # filename without path.       i.e. example.gjf
+    gjf_name=${gjf_file%.*}      # filename without extension.  i.e. example
     
-    cd $gjf_dir  # enter the directory where input file exists
+    cd ${gjf_dir} # change directory
     
     # parse %nprocs and %lindaworkers parameters
     # NOTE! because gjf was turned lowercase before this function, we will match only lowercase!
@@ -78,49 +99,60 @@ genslm_g09_embedded()
     gjf_linda=$(grep -o -P -m 1 '(?<=%lindaworkers=)\d*' $gjf_file)
     
     # print possible warning:
-    if [ "${gjf_nprocs}" -lt 16 ]
+    if [ "${gjf_nprocs}" -lt "${max_nprocs_per_node}" ]
         then
-            printf "${Yellow}${Blink}Warning${NC}: ${Green}$1${NC} has ${Green}%%nprocs${NC}=${Yellow}$gjf_nprocs${NC} less than ${Red}12${NC}.\n"
-            printf "${Yellow}${Blink}Warning${NC}: This may result in inefficient node usage.\n"
+            printf "${Yellow}${Blink}Warning${NC}: ${Green}$1${NC} has ${Green}%%nprocs${NC}=${Yellow}$gjf_nprocs${NC} less than ${Red}${max_nprocs_per_node}${NC}.\n"
+            printf "${Yellow}${Blink}Warning${NC}: You are NOT using nodes exclusively. Recalibration recommended.\n"
     fi
     
     if [ "${gjf_linda}" -gt 1 ]
         then
             printf "${Yellow}${Blink}Warning${NC}: ${Green}$1${NC} has ${Green}%%lindaworkers${NC} more than ${Red}1${NC}.\n"
-            printf "${Yellow}${Blink}Warning${NC}: You may want to check maximum ${Green}%%lindaworkers${NC} depending on each queue.\n"
+            printf "${Yellow}${Blink}Warning${NC}: You may want to check maximum ${Green}%%lindaworkers${NC} of each queue.\n"
     fi
     
-    # prepare sub file lines >>>
+    # prepare sub file variables >>>
     
-    # 2. queue line:
+    # 1. queue line:
     if [ -n "${queue}" ]    # if $queue is defined:
         then
             slm_queue="${queue}"
         else
-            slm_queue="cpu"  # default queue
+            slm_queue="${default_queue}"  # change this in the beginning of the script
     fi
     
-    # 4. cpus line:
+    # 2. cpus line:
     slm_cpus=`echo ${gjf_linda}*${gjf_nprocs} | bc`
-    
-    # prepare sub file lines <<<
-    
-    # copy template file and modify it >>>
-    cp ~/bin/genslm_g09_template sub_g09_${gjf_name}.sh
-    
-    sed -i s/g09_wxl_GENSLM_JOBNAME/"${gjf_name}"/ sub_g09_${gjf_name}.sh
-    sed -i s/GENSLM_QUEUE/"${slm_queue}"/ sub_g09_${gjf_name}.sh
-    sed -i s/GENSLM_CPUS/"${slm_cpus}"/ sub_g09_${gjf_name}.sh
-    sed -i s/GENSLM_INPUTFILE/"${gjf_file}"/ sub_g09_${gjf_name}.sh
-	# copy template file and modifies it <<<
 
-    # other modifications to the sub script:
-    sed -i '4,5d' sub_g09_${gjf_name}.sh #disable .out/.err file output.
+    # writing SLM submit script >>>
+    submit_script=sub_gauss_${gjf_name}.sh
+    rm sub_gauss_${gjf_name}.sh 2> /dev/null
+    
+    touch sub_gauss_${gjf_name}.sh
+    
+    echo -e "#!/bin/bash\n"                                    >> sub_gauss_${gjf_name}.sh
+    
+    echo -e "#SBATCH --job-name=${gjf_name}"                   >> sub_gauss_${gjf_name}.sh
+    echo -e "#SBATCH --output=${gjf_name}_%j.info"             >> sub_gauss_${gjf_name}.sh
+    echo -e "#SBATCH --error=${gjf_name}_%j.info"              >> sub_gauss_${gjf_name}.sh
+    echo -e "#SBATCH -p ${slm_queue}"                          >> sub_gauss_${gjf_name}.sh
+    echo -e "#SBATCH -n ${slm_cpus}"                           >> sub_gauss_${gjf_name}.sh
+    echo -e "#SBATCH --ntasks-per-node=${slm_cpus}"            >> sub_gauss_${gjf_name}.sh
+    echo -e "#SBATCH --time=168:00:00"                         >> sub_gauss_${gjf_name}.sh
+    echo -e "#SBATCH --exclusive\n"                            >> sub_gauss_${gjf_name}.sh
+        
+    echo -e "rm ${gjf_name}_*.info\n"                            >> sub_gauss_${gjf_name}.sh
+
+    echo -e "${EXE} ${gjf_file}\n"                             >> sub_gauss_${gjf_name}.sh
+    # writing SLM submit script complete >>>
 }
+
+
 
 # >>> Main execution starts here >>>
 if_submit=true  # flag: whether to submit through sbatch.
 input_file=false    # flag: whether at least 1 gjf is imported.
+gauss_ver=g09D01    # Gaussian Version set default to g09D01
 
 if [ "$1" != "" ]   # if arguments / files are imported.
     then
@@ -130,6 +162,10 @@ if [ "$1" != "" ]   # if arguments / files are imported.
                     -h | --help )   # help
                         usage
                         exit 0
+                        ;;
+                    -g | --gauss )  # Gaussian Version
+                        shift
+                        gauss_ver=$1
                         ;;
                     -p | --nprocs ) # CPU core numbers.
                         shift
@@ -241,16 +277,49 @@ if [ "$1" != "" ]   # if arguments / files are imported.
                                         fi
                                 fi
                                 # parm overwrite completed <<<<
+                                
+                                # export Gaussian ENV variables >>>>
 
-                                # generate sub_g09_xxx.sh files after .gjf is ready
-                                genslm_g09_embedded $1         # generate .sh submission file
-                                submit_sh="sub_g09_${1%.*}.sh" # locate sub_g09_xxx.sh filename
+                                # !!!Tweak this part if new versions are added.!!!
+                                case $gauss_ver in
+                                    g09C01 )
+                                        export g09root=$g09C01_root
+                                        source $g09C01_profile
+                                        EXE=$(which g09)
+                                        ;;
+                                    g09D01 )
+                                        export g09root=$g09D01_root
+                                        source $g09D01_profile
+                                        EXE=$(which g09)
+                                        ;;
+                                    g09E01 )
+                                        export g09root=$g09E01_root
+                                        source $g09E01_profile
+                                        EXE=$(which g09)
+                                        ;;
+                                    g16A03 )
+                                        export g16root=$g16A03_root
+                                        source $g16A03_profile
+                                        EXE=$(which g16)
+                                        ;;
+                                    * )
+                                        printf "${Red}${Blink}Error:${NC} Gaussian Version NOT defined.\n"
+                                        printf "${Green}Info${NC}: Type ${Blue}\'Submit [-h | --help]\'${NC} for help.\n"
+                                        exit 1
+                                esac
+                                # !!!Tweak this part if new versions are added.!!!
+                                
+                                # export Gaussian ENV variables completed <<<<  
+                                
+                                # generate sub_gauss_xxx.sh files after .gjf is ready
+                                gen_gauss_embedded $1         # generate .sh submission file
+                                submit_sh="sub_gauss_${1%.*}.sh" # locate sub_gauss_xxx.sh filename
                                 
                                 # submit
                                 if [ "$if_submit" = true ]
                                     then
                                         id=$(sbatch ${submit_sh} | awk '{print $4}') # submit job to sbatch, return id.
-                                        rm "sub_g09_${1%.*}.sh" # trash submission file
+                                        rm "sub_gauss_${1%.*}.sh" # trash submission file
                                         printf "${Green}Info${NC}: ${Green}$1${NC} submitted as job ${Red}${id}${NC}.(Queued)\n"
                                     else
                                         printf "${Yellow}${Blink}Warning${NC}: ${Green}$1${NC} NOT submitted.\n"
@@ -276,7 +345,5 @@ if [ "$1" != "" ]   # if arguments / files are imported.
         usage
         exit 1
 fi
-
 exit 0
-
 # <<< Main execution completed <<<
